# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/query.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import types_pb2 as proto_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/query.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11proto/query.proto\x1a\x11proto/types.proto\"j\n\x0fQueryProperties\x12\x15\n\x05Shape\x18\x01 \x01(\x0b\x32\x06.Shape\x12\x19\n\x07\x46ilters\x18\x02 \x01(\x0b\x32\x08.Filters\x12%\n\rPresetFilters\x18\x03 \x01(\x0b\x32\x0e.PresetFilters\"+\n\x12QueryCountResponse\x12\x15\n\rPropertyCount\x18\x01 \x01(\x03\"K\n\x11QueryListResponse\x12\x1f\n\nProperties\x18\x01 \x01(\x0b\x32\x0b.Properties\x12\x15\n\rPropertyCount\x18\x02 \x01(\x03\"Q\n\x15LongQueryListResponse\x12\x1f\n\nProperties\x18\x01 \x01(\x0b\x32\x0b.Properties\x12\x17\n\x06\x44\x65tail\x18\x02 \x01(\x0b\x32\x07.Detail2\xc6\x01\n\x05Query\x12:\n\x0f\x43ountProperties\x12\x10.QueryProperties\x1a\x13.QueryCountResponse\"\x00\x12\x38\n\x0eListProperties\x12\x10.QueryProperties\x1a\x12.QueryListResponse\"\x00\x12G\n\x19ListPropertiesWithDetails\x12\x10.QueryProperties\x1a\x16.LongQueryListResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[proto_dot_types__pb2.DESCRIPTOR,])




_QUERYPROPERTIES = _descriptor.Descriptor(
  name='QueryProperties',
  full_name='QueryProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Shape', full_name='QueryProperties.Shape', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Filters', full_name='QueryProperties.Filters', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PresetFilters', full_name='QueryProperties.PresetFilters', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=146,
)


_QUERYCOUNTRESPONSE = _descriptor.Descriptor(
  name='QueryCountResponse',
  full_name='QueryCountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PropertyCount', full_name='QueryCountResponse.PropertyCount', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=191,
)


_QUERYLISTRESPONSE = _descriptor.Descriptor(
  name='QueryListResponse',
  full_name='QueryListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Properties', full_name='QueryListResponse.Properties', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PropertyCount', full_name='QueryListResponse.PropertyCount', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=268,
)


_LONGQUERYLISTRESPONSE = _descriptor.Descriptor(
  name='LongQueryListResponse',
  full_name='LongQueryListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Properties', full_name='LongQueryListResponse.Properties', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Detail', full_name='LongQueryListResponse.Detail', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=351,
)

_QUERYPROPERTIES.fields_by_name['Shape'].message_type = proto_dot_types__pb2._SHAPE
_QUERYPROPERTIES.fields_by_name['Filters'].message_type = proto_dot_types__pb2._FILTERS
_QUERYPROPERTIES.fields_by_name['PresetFilters'].message_type = proto_dot_types__pb2._PRESETFILTERS
_QUERYLISTRESPONSE.fields_by_name['Properties'].message_type = proto_dot_types__pb2._PROPERTIES
_LONGQUERYLISTRESPONSE.fields_by_name['Properties'].message_type = proto_dot_types__pb2._PROPERTIES
_LONGQUERYLISTRESPONSE.fields_by_name['Detail'].message_type = proto_dot_types__pb2._DETAIL
DESCRIPTOR.message_types_by_name['QueryProperties'] = _QUERYPROPERTIES
DESCRIPTOR.message_types_by_name['QueryCountResponse'] = _QUERYCOUNTRESPONSE
DESCRIPTOR.message_types_by_name['QueryListResponse'] = _QUERYLISTRESPONSE
DESCRIPTOR.message_types_by_name['LongQueryListResponse'] = _LONGQUERYLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryProperties = _reflection.GeneratedProtocolMessageType('QueryProperties', (_message.Message,), {
  'DESCRIPTOR' : _QUERYPROPERTIES,
  '__module__' : 'proto.query_pb2'
  # @@protoc_insertion_point(class_scope:QueryProperties)
  })
_sym_db.RegisterMessage(QueryProperties)

QueryCountResponse = _reflection.GeneratedProtocolMessageType('QueryCountResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYCOUNTRESPONSE,
  '__module__' : 'proto.query_pb2'
  # @@protoc_insertion_point(class_scope:QueryCountResponse)
  })
_sym_db.RegisterMessage(QueryCountResponse)

QueryListResponse = _reflection.GeneratedProtocolMessageType('QueryListResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYLISTRESPONSE,
  '__module__' : 'proto.query_pb2'
  # @@protoc_insertion_point(class_scope:QueryListResponse)
  })
_sym_db.RegisterMessage(QueryListResponse)

LongQueryListResponse = _reflection.GeneratedProtocolMessageType('LongQueryListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LONGQUERYLISTRESPONSE,
  '__module__' : 'proto.query_pb2'
  # @@protoc_insertion_point(class_scope:LongQueryListResponse)
  })
_sym_db.RegisterMessage(LongQueryListResponse)



_QUERY = _descriptor.ServiceDescriptor(
  name='Query',
  full_name='Query',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=354,
  serialized_end=552,
  methods=[
  _descriptor.MethodDescriptor(
    name='CountProperties',
    full_name='Query.CountProperties',
    index=0,
    containing_service=None,
    input_type=_QUERYPROPERTIES,
    output_type=_QUERYCOUNTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListProperties',
    full_name='Query.ListProperties',
    index=1,
    containing_service=None,
    input_type=_QUERYPROPERTIES,
    output_type=_QUERYLISTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListPropertiesWithDetails',
    full_name='Query.ListPropertiesWithDetails',
    index=2,
    containing_service=None,
    input_type=_QUERYPROPERTIES,
    output_type=_LONGQUERYLISTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERY)

DESCRIPTOR.services_by_name['Query'] = _QUERY

# @@protoc_insertion_point(module_scope)
