# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/query.proto

require 'google/protobuf'

require 'proto/types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/query.proto", :syntax => :proto3) do
    add_message "QueryProperties" do
      optional :Shape, :message, 1, "Shape"
      optional :Filters, :message, 2, "Filters"
      optional :PresetFilters, :message, 3, "PresetFilters"
    end
    add_message "QueryCountResponse" do
      optional :PropertyCount, :int64, 1
    end
    add_message "QueryListResponse" do
      optional :Properties, :message, 1, "Properties"
      optional :PropertyCount, :int64, 2
    end
    add_message "LongQueryListResponse" do
      optional :Properties, :message, 1, "Properties"
      optional :Detail, :message, 2, "Detail"
    end
  end
end

QueryProperties = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QueryProperties").msgclass
QueryCountResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QueryCountResponse").msgclass
QueryListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QueryListResponse").msgclass
LongQueryListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LongQueryListResponse").msgclass
