# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/types.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/types.proto", :syntax => :proto3) do
    add_message "Point" do
      optional :latitude, :float, 1
      optional :longitude, :float, 2
    end
    add_message "Shape" do
      repeated :point, :message, 1, "Point"
    end
    add_message "Filter" do
      optional :Field, :string, 1
      optional :symbol, :string, 2
      optional :value, :string, 3
    end
    add_message "Filters" do
      repeated :filter, :message, 1, "Filter"
    end
    add_message "PresetFilter" do
      optional :filterId, :int32, 1
    end
    add_message "PresetFilters" do
      repeated :filter, :message, 1, "PresetFilter"
    end
    add_message "PropertyId" do
      optional :propertyId, :int64, 1
    end
    add_message "Properties" do
      repeated :property, :message, 1, "PropertyId"
    end
    add_message "Detail" do
      optional :Beds, :string, 1
    end
  end
end

Point = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Point").msgclass
Shape = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Shape").msgclass
Filter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Filter").msgclass
Filters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Filters").msgclass
PresetFilter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PresetFilter").msgclass
PresetFilters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PresetFilters").msgclass
PropertyId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PropertyId").msgclass
Properties = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Properties").msgclass
Detail = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Detail").msgclass
